version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - '${PGPORT}:5432'
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
