name: audit

on:
  pull_request:
    branches:
      - main

jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run audit
        run: npm audit --omit=dev
